apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:gpu-nvidia-latest
          ports:
            - containerPort: 6333  # HTTP API
            - containerPort: 6334  # gRPC
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          emptyDir: {}  # For production, replace with PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  type: NodePort
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      nodePort: 30333
    - name: grpc
      port: 6334
      targetPort: 6334
      nodePort: 30334
